name: Check title of pull request
on:
    pull_request_target:
        types:
            - opened
            - reopened
            - edited
            - synchronize

jobs:
    check:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
        steps:
            - name: Aron Actions
              uses: techor-dev/techor@v2.5.17
              with:
                  action: "check-pull-request-title"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
